# Generated by Django 2.2 on 2019-05-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pitches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba', models.IntegerField(blank=True, null=True)),
                ('sku_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ean', models.FloatField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('flavor', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255, null=True)),
                ('size', models.CharField(max_length=255)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('depth', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'pitches',
                'verbose_name_plural': 'pitches',
            },
        ),
    ]
